# -*- coding: utf-8 -*-
"""London Housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFvnz4ZLCsS1Q58f-t16IaO9uA2_R0PN
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd
file_path = '/content/drive/My Drive/london_housing.csv'

df=pd.read_csv(file_path)
df.head()

df

df.count()

df.isnull()

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt
import plotly as px

sns.heatmap(df.isnull())
plt.show

import plotly.express as px

missing_data = df.isnull()
missing_data_int = missing_data.astype(int)

fig = px.imshow(missing_data_int,
                labels=dict(x="Columns", y="Rows", color="Missing"),
                color_continuous_scale='Viridis')

fig.update_layout(title="Heatmap of Missing Values")

fig.show()

df.head(10)

df.dtypes

"""df.date = pd.to_datetime(df.date)"""

df

df.dtypes

df.date = pd.to_datetime(df.date)
df['year']=df.date.dt.year

df

df

df.drop(['month', 'year'], axis = 1, inplace = True)
df

len(df[df.no_of_crimes == 0])

"""# What is the maximum & minimum 'average_price' per year in England?"""

df['year']=df.date.dt.year
df

df1 = df[df.area == 'england']
df1

df1.groupby('year')

df1.groupby('year')['average_price'].max()

df1.groupby('year')['average_price'].min()

df1.groupby('year')['average_price'].mean()

"""#What is the Max. & Min. No. of Crimes recorded per area?"""

df.groupby('area')

df

df.groupby('area').no_of_crimes.max()

df.groupby('area').no_of_crimes.min().sort_values(ascending = False)

df.groupby('area').no_of_crimes.mean()